version: 2.1

commands:
  release_app:
    steps:
      - checkout
      - run:
          command: |
            yarn install
            yarn semantic-release

jobs:
  release_job:
    build:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - release_app

workflows:
  release_workflow:
    jobs:
      - release_job:
          context: general_context
          filters:
            branches:
              only: main
