version: 2.1

orbs:
  node: circleci/node@4.5

commands:
  release_app:
    steps:
      - checkout
      - run:
          command: |
            sudo npm install -g yarn
            sudo yarn
            sudo yarn semantic-release

jobs:
  release_job:
    executor: node/default
    steps:
      - release_app

workflows:
  release_workflow:
    jobs:
      - release_job:
          context: general_context
          filters:
            branches:
              only: main
